#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2019, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#


#
# Format the data disc on each Kafka node.
#

---
- hosts: kafkas
  gather_facts: false

  vars:
    devpath: '/dev/vdc'
    mntpath: '/data-vdc'

  tasks:

#   - stat:
#       path: "{{devpath}}"
#     register: devstat
#
#   - stat:
#       path: "{{mntpath}}"
#     register: mntstat
#
#   - debug:
#       msg: "Before dev stat {{devstat}}"
#
#   - debug:
#       msg: "Before mnt stat {{mntstat}}"

    # TODO Only do this if not already created
    - name: "Create a btrfs filesystem on {{devpath}}"
      become: true
      filesystem:
        fstype: btrfs
        dev: "{{devpath}}"

    # TODO Only do this if not already created
    - name: "Create the mount point {{mntpath}}"
      become: true
      file:
        path: "{{mntpath}}"
        state: directory

    # TODO Only do this if not already mounted
    - name: "Create the mount-failed indicator"
      become: true
      file:
        path: "{{mntpath}}/mount-failed"
        state: touch
        mode:  u=r,g=r,o=r

    # TODO Only do this if not already mounted
    # TODO Mount using UUID rather than device path.
    - name: "Mount device {{ devpath }} as {{mntpath}}"
      become: true
      mount:
        src:  "{{devpath}}"
        path: "{{mntpath}}"
        fstype: btrfs
        state:  mounted

#   - stat:
#       path: "{{devpath}}"
#     register: devstat
#
#   - stat:
#       path: "{{mntpath}}"
#     register: mntstat

#   - debug:
#       msg: "After dev stat {{devstat}}"
#
#   - debug:
#       msg: "After mnt stat {{mntstat}}"

    - command:
        argv:
          - 'df'
          - '--human-readable'
          - "{{mntpath}}"
      register: dfcheck

    - debug:
        msg: "After space {{dfcheck}}"

