#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2019, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#

#
# Installing Docker Engine on Fedora using Ansible.
# http://www.mydailytutorials.com/docker-engine-fedora-25-ansible/
#

---
- hosts: dockers
  gather_facts: false

  tasks:

  - name: "Remove Fedora Docker packages"
    become: true
    dnf:
      name: [
        'docker',
        'docker-common',
        'docker-selinux',
        'container-selinux'
        ]
      state: absent

  - name: "Check dnf-plugins-core is installed"
    become: true
    dnf:
      name:  dnf-plugins-core
      state: present

  - name: "Add the Docker-CE dnf repository"
    become: true
    command:
      argv:
        - 'dnf',
        - 'config-manager',
        - '--add-repo',
        - 'https://download.docker.com/linux/fedora/docker-ce.repo'

  - name: "Check Docker-CE is installed"
    become: true
    dnf:
     name:  docker-ce
     state: latest

  - name: "Check Docker service is enabled and started"
    become: true
    systemd:
      enabled: true
      name:  docker
      state: started

  - name: "Install Python Docker libraries for Ansible to use"
    become: true
    pip:
      name: [
          'docker',
          'docker-compose'
          ]

