version: "3.2"

services:

    emily:
        image:
            "confluentinc/cp-kafka:4.1.1"
        restart:
            "no"
        ports:
            - "9092:9092"
            - "9093:9093"
        extra_hosts:
            - "${KAFKA_HOSTNAME}:127.0.0.2"
        environment:
            - "KAFKA_LISTENERS=jasminum://0.0.0.0:9092"
            - "KAFKA_ADVERTISED_LISTENERS=jasminum://${KAFKA_HOSTNAME}:9092"
            - "KAFKA_INTER_BROKER_LISTENER_NAME=jasminum"
            - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=jasminum:PLAINTEXT"
            - "KAFKA_LOG_DIRS=${KAFKA_LOG_DIRS}"
            - "KAFKA_BROKER_ID=${KAFKA_BROKER_ID}"
            - "KAFKA_BROKER_RACK=${KAFKA_BROKER_RACK}"
            - "KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}"
            - "KAFKA_NUM_PARTITIONS=16"
            - "KAFKA_DEFAULT_REPLICATION_FACTOR=3"
            - "KAFKA_LOG_RETENTION_MS=-1"
            - "KAFKA_LOG_RETENTION_BYTES=-1"
            - "KAFKA_AUTO_CREATE_TOPICS_ENABLE=true"
            - "KAFKA_MESSAGE_MAX_BYTES=10485760"
        volumes:
            - type:   "bind"
              source: "${volmnt}"
              target: "${volmnt}"

